# -*- coding: utf-8 -*-
"""Smart_Campus_AI_Training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bIECCrQvMyHN2UncDuuJGlHBKr8qaGBw

## Environment Setup
"""

!pip install torch torchvision
!pip install transformers
!pip install openai-whisper
!pip install opencv-python
!pip install librosa
!pip install faiss-cpu
!pip install jiwer
!pip install scikit-learn
!pip install datasets
!pip install accelerate
!pip install soundfile

"""## Import Libraries"""

import os
import json
import pickle
import zipfile
import shutil
import cv2
import torch
import whisper
import librosa
import librosa.display
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import faiss
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from transformers import (
    CLIPProcessor,
    CLIPModel,
    DistilBertTokenizerFast,
    DistilBertForSequenceClassification,
    Trainer,
    TrainingArguments
)
from torch.utils.data import Dataset
from jiwer import wer

"""## Mount Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

PROJECT_PATH = "/content/drive/MyDrive/Smart_Campus_Multimodal_AI_Assistant"
print("Project path set to:", PROJECT_PATH)

"""### Unzip Dataset"""

zip_path = PROJECT_PATH + "/Smart_Campus_Multimodal_AI_Assistant.zip"
extract_path = PROJECT_PATH

if os.path.exists(zip_path):
    with zipfile.ZipFile(zip_path, 'r') as z:
        z.extractall(extract_path)
    print("Dataset extracted successfully.")
else:
    print("Zip file not found. Assuming dataset is already extracted.")

"""## Data Acquisition and Exploration

### Image Dataset Analysis
"""

image_path = PROJECT_PATH + "/dataset/images"
classes = [c for c in os.listdir(image_path) if os.path.isdir(os.path.join(image_path, c))]
counts = {}
for c in classes:
    counts[c] = len(os.listdir(os.path.join(image_path, c)))
print("Classes found:", list(counts.keys()))
print("Image counts:", counts)

"""### Campus Image Class Distribution"""

plt.figure(figsize=(12, 5))
plt.bar(counts.keys(), counts.values(), color='steelblue', edgecolor='black')
plt.xticks(rotation=45, ha='right')
plt.title("Campus Image Class Distribution")
plt.xlabel("Location Category")
plt.ylabel("Number of Images")
plt.tight_layout()
plt.savefig(PROJECT_PATH + "/class_distribution.png", dpi=150)
plt.show()

"""### Sample Image Display"""

for folder in classes[:3]:
    folder_path = os.path.join(image_path, folder)
    img_file = os.listdir(folder_path)[0]
    img = cv2.imread(os.path.join(folder_path, img_file))
    plt.figure(figsize=(4, 4))
    plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    plt.title(folder)
    plt.axis('off')
    plt.tight_layout()
    plt.show()

"""### Voice and Text Data Exploration"""

audio_base = PROJECT_PATH + "/dataset/audio"
intent_folders = os.listdir(audio_base)
audio_counts = {}
for intent in intent_folders:
    intent_path = os.path.join(audio_base, intent)
    if os.path.isdir(intent_path):
        audio_counts[intent] = len(os.listdir(intent_path))
print("Audio intent counts:", audio_counts)

plt.figure(figsize=(8, 4))
plt.bar(audio_counts.keys(), audio_counts.values(), color='darkorange', edgecolor='black')
plt.title("Audio Query Distribution by Intent")
plt.xlabel("Intent")
plt.ylabel("Number of Audio Files")
plt.xticks(rotation=30, ha='right')
plt.tight_layout()
plt.show()

faq = pd.read_csv(PROJECT_PATH + "/dataset/text/campus_queries.csv")
print("Shape:", faq.shape)
print(faq.head(10))

faq['intent'].value_counts().plot(kind='bar', figsize=(8, 4), color='mediumseagreen', edgecolor='black')
plt.title("Intent Distribution in Campus Query Dataset")
plt.xlabel("Intent")
plt.ylabel("Count")
plt.xticks(rotation=30, ha='right')
plt.tight_layout()
plt.show()

"""### Campus Knowledge Base"""

kb = json.load(open(PROJECT_PATH + "/dataset/knowledge_base/campus_database.json"))
print(f"Total knowledge base records: {len(kb)}")
for rec in kb[:3]:
    print(json.dumps(rec, indent=2))

"""## Preprocessing

### Image Preprocessing Pipeline
"""

from torchvision import transforms, datasets
from torch.utils.data import DataLoader

image_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.RandomRotation(15),
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

val_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

full_dataset = datasets.ImageFolder(root=image_path, transform=image_transform)
print("Classes:", full_dataset.classes)
print("Total images:", len(full_dataset))

train_size = int(0.8 * len(full_dataset))
val_size = len(full_dataset) - train_size
train_dataset, val_dataset = torch.utils.data.random_split(full_dataset, [train_size, val_size])

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False)
print(f"Train: {len(train_dataset)} | Val: {len(val_dataset)}")

"""### Sample Preprocessed Images"""

import torchvision
sample_batch, sample_labels = next(iter(train_loader))
grid = torchvision.utils.make_grid(sample_batch[:8], nrow=4, normalize=True)
plt.figure(figsize=(12, 4))
plt.imshow(grid.permute(1, 2, 0).numpy())
plt.title("Sample Preprocessed Training Images")
plt.axis('off')
plt.show()

"""### Audio Preprocessing Pipeline"""

audio_path = PROJECT_PATH + "/dataset/audio/find_location/find_location_1.wav"
audio, sr = librosa.load(audio_path, sr=None)
print(f"Sample rate: {sr} | Duration: {len(audio)/sr:.2f}s")

plt.figure(figsize=(10, 3))
librosa.display.waveshow(audio, sr=sr)
plt.title("Audio Waveform - find_location_1.wav")
plt.xlabel("Time (s)")
plt.ylabel("Amplitude")
plt.tight_layout()
plt.show()

mfcc = librosa.feature.mfcc(y=audio, sr=sr, n_mfcc=13)
plt.figure(figsize=(10, 4))
plt.imshow(mfcc, aspect='auto', origin='lower', cmap='viridis')
plt.colorbar(label='MFCC Coefficient Value')
plt.title("MFCC Features - find_location_1.wav")
plt.xlabel("Time Frames")
plt.ylabel("MFCC Coefficients")
plt.tight_layout()
plt.show()

"""### Text Preprocessing Pipeline"""

import re
import string

STOPWORDS = {'a','an','the','is','in','at','of','to','and','or','for','on','are','was','it','with'}

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z0-9\s]', '', text)
    tokens = text.split()
    tokens = [t for t in tokens if t not in STOPWORDS]
    return " ".join(tokens)

faq['cleaned'] = faq['query'].apply(clean_text)
print(faq[['query','cleaned','intent']].head(10))

label2id = {label: i for i, label in enumerate(sorted(faq['intent'].unique()))}
id2label = {i: label for label, i in label2id.items()}
faq['label'] = faq['intent'].map(label2id)
print("Label mapping:", label2id)

train_df, val_df = train_test_split(faq, test_size=0.2, random_state=42, stratify=faq['label'])
print(f"Train: {len(train_df)} | Val: {len(val_df)}")

"""## CLIP and FAISS Vision Model"""

clip_model = CLIPModel.from_pretrained("openai/clip-vit-base-patch32")
processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")
clip_model.eval()
print("CLIP model loaded successfully.")

embeddings = []
labels = []
for folder in classes:
    folder_path = os.path.join(image_path, folder)
    files = [f for f in os.listdir(folder_path) if f.lower().endswith(('.jpg','.jpeg','.png'))]
    for file in files[:15]:
        img = Image.open(os.path.join(folder_path, file)).convert("RGB")
        inputs = processor(images=img, return_tensors="pt")
        with torch.no_grad():
            output = clip_model.vision_model(**inputs)
        vec = output.pooler_output.detach().numpy()[0]
        embeddings.append(vec)
        labels.append(folder)
embeddings = np.array(embeddings).astype("float32")
faiss.normalize_L2(embeddings)
print(f"Total embeddings: {embeddings.shape[0]} | Dim: {embeddings.shape[1]}")

index = faiss.IndexFlatIP(embeddings.shape[1])
index.add(embeddings)
print(f"FAISS index size: {index.ntotal}")

os.makedirs(PROJECT_PATH + "/saved_models/faiss_index", exist_ok=True)
faiss.write_index(index, PROJECT_PATH + "/saved_models/faiss_index/campus.index")
pickle.dump(labels, open(PROJECT_PATH + "/saved_models/faiss_index/location_mapping.pkl", "wb"))
print("FAISS index and label mapping saved.")

"""## Whisper Speech Model"""

whisper_model = whisper.load_model("base")
print("Whisper model loaded successfully.")

result = whisper_model.transcribe(audio_path)
print("Transcription:", result["text"])

all_transcripts = []
reference_texts = []

for intent in os.listdir(audio_base):
    intent_path = os.path.join(audio_base, intent)
    if not os.path.isdir(intent_path):
        continue
    for fname in os.listdir(intent_path)[:3]:
        fpath = os.path.join(intent_path, fname)
        res = whisper_model.transcribe(fpath)
        all_transcripts.append(res["text"])
        print(f"[{intent}] {fname}: {res['text']}")

"""## DistilBERT Intent Classifier"""

tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")

class CampusDataset(Dataset):
    def __init__(self, df, tokenizer, max_len=64):
        self.encodings = tokenizer(list(df['cleaned']), truncation=True, padding=True, max_length=max_len)
        self.labels = list(df['label'])
    def __len__(self):
        return len(self.labels)
    def __getitem__(self, idx):
        item = {k: torch.tensor(v[idx]) for k, v in self.encodings.items()}
        item['labels'] = torch.tensor(self.labels[idx])
        return item

train_dataset_bert = CampusDataset(train_df, tokenizer)
val_dataset_bert = CampusDataset(val_df, tokenizer)
print(f"DistilBERT train size: {len(train_dataset_bert)} | val size: {len(val_dataset_bert)}")

num_labels = len(label2id)
bert_model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=num_labels,
    id2label=id2label,
    label2id=label2id
)

os.makedirs(PROJECT_PATH + "/saved_models/distilbert", exist_ok=True)

training_args = TrainingArguments(
    output_dir=PROJECT_PATH + "/saved_models/distilbert",
    num_train_epochs=5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    warmup_steps=20,
    weight_decay=0.01,
    logging_dir=PROJECT_PATH + "/logs",
    logging_steps=10,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    report_to="none"
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {"accuracy": accuracy_score(labels, preds)}

trainer = Trainer(
    model=bert_model,
    args=training_args,
    train_dataset=train_dataset_bert,
    eval_dataset=val_dataset_bert,
    compute_metrics=compute_metrics
)

trainer.train()
print("DistilBERT training complete.")

bert_model.save_pretrained(PROJECT_PATH + "/saved_models/distilbert")
tokenizer.save_pretrained(PROJECT_PATH + "/saved_models/distilbert")
print("DistilBERT model and tokenizer saved.")

"""### Training Loss Curve"""

log_history = trainer.state.log_history
train_loss = [(e['epoch'], e['loss']) for e in log_history if 'loss' in e]
val_loss = [(e['epoch'], e['eval_loss']) for e in log_history if 'eval_loss' in e]

plt.figure(figsize=(10, 4))
if train_loss:
    plt.plot([x[0] for x in train_loss], [x[1] for x in train_loss], label='Train Loss')
if val_loss:
    plt.plot([x[0] for x in val_loss], [x[1] for x in val_loss], label='Val Loss')
plt.title("DistilBERT Training and Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.tight_layout()
plt.savefig(PROJECT_PATH + "/training_loss_curve.png", dpi=150)
plt.show()

"""## Evaluation

### CLIP Top-1 and Top-3 Retrieval Accuracy
"""

test_embeddings = []
test_labels = []

for folder in classes:
    folder_path = os.path.join(image_path, folder)
    files = [f for f in os.listdir(folder_path) if f.lower().endswith(('.jpg','.jpeg','.png'))]
    for file in files[15:20]:
        img = Image.open(os.path.join(folder_path, file)).convert("RGB")
        inputs = processor(images=img, return_tensors="pt")
        with torch.no_grad():
            output = clip_model.vision_model(**inputs)
        vec = output.pooler_output.detach().numpy()[0].astype("float32")
        vec = vec / np.linalg.norm(vec)
        test_embeddings.append(vec)
        test_labels.append(folder)

test_embeddings = np.array(test_embeddings).astype("float32")

top1_correct = 0
top3_correct = 0
for i, (vec, true_label) in enumerate(zip(test_embeddings, test_labels)):
    D, I = index.search(vec.reshape(1, -1), 3)
    retrieved = [labels[idx] for idx in I[0]]
    if retrieved[0] == true_label:
        top1_correct += 1
    if true_label in retrieved:
        top3_correct += 1

n = len(test_labels)
print(f"Top-1 Retrieval Accuracy: {top1_correct/n*100:.1f}% ({top1_correct}/{n})")
print(f"Top-3 Retrieval Accuracy: {top3_correct/n*100:.1f}% ({top3_correct}/{n})")

"""### DistilBERT Intent Classification Report"""

preds_output = trainer.predict(val_dataset_bert)
predicted = np.argmax(preds_output.predictions, axis=1)
actual = preds_output.label_ids

print(classification_report(actual, predicted, target_names=list(label2id.keys())))

"""### Whisper Word Error Rate"""

audio_references = {

    "ask_hours_1.wav":
        "what time does the library open",

    "ask_hours_2.wav":
        "when does the cafeteria close",

    "find_event_1.wav":
        "what events are happening today",

    "find_event_2.wav":
        "show upcoming campus events",

    "find_location_1.wav":
        "where is the library",

    "find_location_2.wav":
        "find the computer room",

    "ask_direction_1.wav":
        "how can i reach the library",

    "ask_direction_2.wav":
        "give directions to cafeteria"

}


hypotheses = []
references = []


for intent in os.listdir(audio_base):

    intent_path = os.path.join(
        audio_base,
        intent
    )

    if not os.path.isdir(intent_path):
        continue


    for fname in os.listdir(intent_path):

        if fname in audio_references:

            fpath = os.path.join(
                intent_path,
                fname
            )


            result = whisper_model.transcribe(
                fpath
            )


            predicted_text = (
                result["text"]
                .lower()
                .strip()
            )


            hypotheses.append(
                predicted_text
            )


            references.append(
                audio_references[fname]
            )


            print(
                "Reference :",
                audio_references[fname]
            )

            print(
                "Whisper  :",
                predicted_text
            )

            print("-"*50)



wer_score = wer(
    references,
    hypotheses
)


print(
    f"\nWhisper Word Error Rate (WER): {wer_score:.4f}"
)

print(
    f"WER Percentage: {wer_score*100:.2f}%"
)

"""## Multimodal Fusion Model"""

import torch.nn as nn

class FusionMLP(nn.Module):
    def __init__(self, image_dim=512, text_dim=768, num_classes=None):
        super().__init__()
        self.image_proj = nn.Linear(image_dim, 256)
        self.text_proj = nn.Linear(text_dim, 256)
        self.fusion = nn.Sequential(
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, num_classes)
        )
    def forward(self, image_emb=None, text_emb=None):
        if image_emb is None:
            image_emb = torch.zeros(text_emb.size(0), 256)
        else:
            image_emb = torch.relu(self.image_proj(image_emb))
        if text_emb is None:
            text_emb = torch.zeros(image_emb.size(0), 256)
        else:
            text_emb = torch.relu(self.text_proj(text_emb))
        combined = torch.cat([image_emb, text_emb], dim=1)
        return self.fusion(combined)

num_classes = len(label2id)
num_classes = len(label2id)

print(
    "Fusion output classes:",
    num_classes
)


fusion_model = FusionMLP(
    image_dim=512,
    text_dim=768,
    num_classes=num_classes
)


print(
    fusion_model
)

from transformers import DistilBertModel

text_encoder = DistilBertModel.from_pretrained("distilbert-base-uncased")
text_encoder.eval()

def get_text_embedding(text):
    enc = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=64)
    with torch.no_grad():
        out = text_encoder(**enc)
    return out.last_hidden_state[:, 0, :]

class FusionDataset(Dataset):
    def __init__(self, df):
        self.texts = list(df['cleaned'])
        self.labels = list(df['label'])
    def __len__(self):
        return len(self.labels)
    def __getitem__(self, idx):
        emb = get_text_embedding(self.texts[idx])
        return emb.squeeze(0), torch.tensor(self.labels[idx])

fusion_train = FusionDataset(train_df)
fusion_val = FusionDataset(val_df)

fusion_train_loader = DataLoader(fusion_train, batch_size=16, shuffle=True)
fusion_val_loader = DataLoader(fusion_val, batch_size=16, shuffle=False)

optimizer = torch.optim.Adam(fusion_model.parameters(), lr=1e-3, weight_decay=1e-4)
scheduler = torch.optim.lr_scheduler.StepLR(optimizer, step_size=3, gamma=0.5)
criterion = nn.CrossEntropyLoss()

train_losses = []
val_accs = []

for epoch in range(10):
    fusion_model.train()
    epoch_loss = 0
    for text_emb, lbl in fusion_train_loader:
        optimizer.zero_grad()
        out = fusion_model(text_emb=text_emb)
        loss = criterion(out, lbl)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
    scheduler.step()

    fusion_model.eval()
    preds, actuals = [], []
    with torch.no_grad():
        for text_emb, lbl in fusion_val_loader:
            out = fusion_model(text_emb=text_emb)
            preds += torch.argmax(out, dim=1).tolist()
            actuals += lbl.tolist()
    acc = accuracy_score(actuals, preds)
    train_losses.append(epoch_loss / len(fusion_train_loader))
    val_accs.append(acc)
    print(f"Epoch {epoch+1:02d} | Loss: {train_losses[-1]:.4f} | Val Acc: {acc*100:.1f}%")

fig, ax1 = plt.subplots(figsize=(10, 4))
ax1.plot(range(1, 11), train_losses, 'b-o', label='Train Loss')
ax1.set_xlabel("Epoch")
ax1.set_ylabel("Loss", color='blue')
ax2 = ax1.twinx()
ax2.plot(range(1, 11), val_accs, 'r-s', label='Val Accuracy')
ax2.set_ylabel("Accuracy", color='red')
plt.title("Fusion MLP Training Loss and Validation Accuracy")
fig.tight_layout()
plt.savefig(PROJECT_PATH + "/fusion_training.png", dpi=150)
plt.show()

os.makedirs(PROJECT_PATH + "/saved_models/fusion", exist_ok=True)
torch.save(fusion_model.state_dict(), PROJECT_PATH + "/saved_models/fusion/fusion_model.pt")
print("Fusion model saved.")

"""## End-to-End Knowledge Base Retrieval Test"""

kb = json.load(open(PROJECT_PATH + "/dataset/knowledge_base/campus_database.json"))
print(f"Knowledge base loaded. Total records: {len(kb)}")
for rec in kb[:3]:
    print(json.dumps(rec, indent=2))

test_queries = [
    ("Is the waiting room open today?", "ask_hours", "waiting room"),
    ("Tell me opening hours of auditorium.", "ask_hours", "auditorium"),
    ("Where can I access the staircase?", "find_location", "staircase"),
    ("Navigate me to waiting room.", "ask_direction", "waiting room"),
    ("What events are happening today?", "find_event", None) # Example with no specific entity
]

def query_kb(intent_label, entity=None):
    name_key = None
    for candidate in ['name', 'building_name', 'location_name', 'title', 'building']:
        if candidate in kb[0]:
            name_key = candidate
            break
    if name_key is None:
        name_key = list(kb[0].keys())[0]

    category_key = None
    for candidate in ['category', 'type', 'building_type', 'kind']:
        if candidate in kb[0]:
            category_key = candidate
            break

    for record in kb:
        rec_name = record.get(name_key, '').lower()
        rec_category = record.get(category_key, '').lower() if category_key else ''
        if intent_label in ("find_location", "ask_direction"):
            if entity and entity.lower() in rec_name:
                return record
            if entity and entity.lower() in rec_category:
                return record
        elif intent_label == "ask_hours":
            if entity and entity.lower() in rec_name:
                return record
        elif intent_label == "find_event":
            # For find_event, we just need to find a record with events
            if record.get('events') or record.get('upcoming_events'):
                return record
    return kb[0]

print(f"{'Query':<50} {'Intent':<20} {'Matched Location'}")
print("-" * 95)
for query, intent, entity in test_queries:
    rec = query_kb(intent, entity)
    name_key = next((k for k in ['name','building_name','location_name','title','building'] if k in rec), list(rec.keys())[0])
    print(f"{query:<50} {intent:<20} {rec[name_key]}")

"""### End-to-End Inference Pipeline"""

locations = [
    rec["folder_name"]
    for rec in kb
]


def extract_entity(text):

    text=text.lower()

    for loc in locations:

        if loc.replace("_"," ") in text:
            return loc

    return None

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
bert_model = bert_model.to(device)
clip_model = clip_model.to(device)

def end_to_end_inference(text_query=None, image_file=None, audio_file=None):
    modality = []
    intent = None
    image_result = None

    if audio_file and os.path.exists(audio_file):
        res = whisper_model.transcribe(audio_file)
        text_query = res["text"]
        modality.append("voice")
        print(f"  Whisper transcript: {text_query}")

    if text_query:
        modality.append("text")
        cleaned = clean_text(text_query)
        enc = tokenizer(cleaned, return_tensors="pt", truncation=True, padding=True, max_length=64)
        enc = {k: v.to(device) for k, v in enc.items()}
        with torch.no_grad():
            logits = bert_model(**enc).logits
        intent_id = torch.argmax(logits, dim=1).item()
        intent = id2label[intent_id]
        print(f"  Detected intent: {intent}")

    if image_file and os.path.exists(image_file):
        modality.append("image")
        img = Image.open(image_file).convert("RGB")
        inputs = processor(images=img, return_tensors="pt")
        inputs = {k: v.to(device) for k, v in inputs.items()}
        with torch.no_grad():
            output = clip_model.vision_model(**inputs)
        vec = output.pooler_output.detach().cpu().numpy()[0].astype("float32")
        vec = vec / np.linalg.norm(vec)
        D, I = index.search(vec.reshape(1, -1), 1)
        image_result = labels[I[0][0]]
        print(f"  CLIP matched location: {image_result}")

    entity = image_result if image_result else (extract_entity(text_query) if text_query else None)
    record = query_kb(intent if intent else "find_location", entity)

    name_key = next((k for k in ['name','building_name','location_name','title','building'] if k in record), list(record.keys())[0])
    print(f"  Modalities used: {modality}")
    print(f"  Knowledge Base Result:")
    print(f"    Location : {record[name_key]}")
    print(f"    Category : {record.get('category','N/A')}")
    print(f"    Hours    : {record.get('opening_hours','N/A')}")
    print(f"    Events   : {record.get('events','None')}")
    print(f"    Directions: {record.get('map_reference','N/A')}")
    return record

print("=== Test 1: Text Query ===")
end_to_end_inference(text_query="Where is the library?")

print("\n=== Test 2: Voice Query ===")
end_to_end_inference(audio_file=audio_path)

"""### End-to-End Accuracy Summary"""

correct = 0
total = len(test_queries)

for query, intent, entity in test_queries:

    rec = query_kb(
        intent,
        entity
    )

    is_current_query_correct = False
    if entity is not None:
        entity_lower = entity.lower()
        if (
            entity_lower in rec.get("building_name", "").lower()
            or
            entity_lower in rec.get("category","").lower()
            or
            entity_lower in rec.get("folder_name","").lower()
        ):
            is_current_query_correct = True
    elif intent == "find_event" and (rec.get('events') or rec.get('upcoming_events')):
        # For 'find_event' with no specific entity, consider it correct if the returned record has events
        is_current_query_correct = True

    if is_current_query_correct:
        correct += 1


kb_accuracy = correct / total * 100


print(
    f"End-to-End KB Retrieval Accuracy: {correct}/{total} = {kb_accuracy:.1f}%"
)


metrics_summary = {

    "CLIP Top-1 Accuracy (%)":
        round(
            top1_correct/n*100,
            1
        ),

    "CLIP Top-3 Accuracy (%)":
        round(
            top3_correct/n*100,
            1
        ),

    "Whisper WER":
        round(
            wer_score,
            4
        ),

    "End-to-End KB Accuracy (%)":
        round(
            kb_accuracy,
            1
        )

}


print(
    "\nFull Evaluation Summary:"
)


for k,v in metrics_summary.items():

    print(
        f"{k}: {v}"
    )